# Generated by Django 3.0.5 on 2020-04-29 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200429_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='announcements', to='courses.Course', verbose_name='Curso'),
        ),
    ]
