# Generated by Django 3.0.5 on 2020-04-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200429_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='courses.Announcements', verbose_name='Anúncio'),
        ),
    ]
